name: Build

on:
  workflow_dispatch:  # manual trigger only

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install SCons
      run: pip install scons

    - name: Install Boost
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libboost-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install boost
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install boost --yes
        fi

    - name: Build with SCons
      run: |
          scons target=template_debug
          scons target=template_release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: template-binaries-${{ matrix.os }}
        path: |
          project/bin/*.so
          project/bin/*.dll
          project/bin/*.dylib
